# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f1ceb35276c597f9c1efd7a6a54f737509b9fccb169aefa8b7364b8c1a0f392f8056c337da1ec592b7d9f481926f808397142412a5e327977f7e99d1da56f3f

test:
  secret_key_base: f674ca310c6aee480ad6296bf36b9d4eb5fd53e3ddfb7010c93f91f283dbaf32e844537b60af2bf1b92310be305945c7b889abf63ac48a3af0070d832cd35c95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
